server:
  assets-path: /app/assets

theme:
  custom-css-file: /assets/user.css

branding:
  custom-footer: |
    <p>Powered by Marreco</p>
  logo-url: /assets/marreco.png

pages:
  - $include: homelab.yml
  - $include: welcome.yml